### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by fox** [intercom/passport-intercom#1]
1. In https://github.com/intercom/passport-intercom/blob/master/lib/passport-intercom/strategy.js#L22  should `https://api.intercom.io/me` come from options so this works in our dev environment (so, like `options.profileURL || 'https://api.intercom.io/me'`)?
2. let's put a new line after the `{` and before `}` in https://github.com/intercom/passport-intercom/blob/master/lib/passport-intercom/strategy.js#L23 😄 
3. since this is public code, do you think we should comment on methods like [facebook strategy](https://github.com/jaredhanson/passport-facebook/blob/master/lib/strategy.js#L115) does? 
4. a few tiny (feel free to ignore) bits about the README: you can make code snippets syntax highlighted by prepending  ```js. Maybe we could add a section explaining creation of application / prerequisites [similar to this](https://github.com/jaredhanson/passport-facebook/blob/master/README.md#create-an-application).

Other than that -- all cool,  ship: Oh, we've already shipped :D

**Comment by rorhug** [comment]
1. Until someone inside the organisation requires this, I feel it's unnecessary. Even I, developing the strategy, wouldn't have needed this. The target developers (outside the company) definitely won't.
2. done https://github.com/intercom/passport-intercom/commit/5f4bd430001d6fe175663206ca15db7e521aa24a
3. done https://github.com/intercom/passport-intercom/commit/c4d1e5fdf0604ac3b72450f945c7d55c7db2a483
4. done https://github.com/intercom/passport-intercom/commit/fbe1aaaee26230adb9aa380133c0dd07721f88df

**Comment by fox** [comment]
Thanks! I agree with 1) - definitely not needed for devs outside the company.
